name: flutter_dotenv
version: 4.1.0
description: Easily configure any flutter application with global variables using a `.env` file.
author: java-james <james-collins@hotmail.co.nz>
homepage: https://github.com/java-james/flutter_dotenv
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
